# Generated by Django 5.0.2 on 2024-02-17 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=36, unique=True)),
                ('platform', models.IntegerField()),
                ('_modified', models.DateTimeField()),
                ('fin', models.CharField(blank=True, max_length=100)),
                ('sea', models.BooleanField(default=False)),
                ('tmg', models.BooleanField(default=False)),
                ('efis', models.BooleanField(default=False)),
                ('fnpt', models.IntegerField(default=0)),
                ('make', models.CharField(max_length=100)),
                ('run2', models.BooleanField(default=False)),
                ('aircraft_class', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('power', models.IntegerField()),
                ('seats', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('kg5700', models.BooleanField(default=False)),
                ('rating', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('complex', models.BooleanField(default=False)),
                ('cond_log', models.IntegerField()),
                ('fav_list', models.BooleanField(default=False)),
                ('category', models.IntegerField()),
                ('high_perf', models.BooleanField(default=False)),
                ('sub_model', models.CharField(blank=True, max_length=100)),
                ('aerobatic', models.BooleanField(default=False)),
                ('ref_search', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('tailwheel', models.BooleanField(default=False)),
                ('default_app', models.IntegerField()),
                ('default_log', models.IntegerField()),
                ('default_ops', models.IntegerField()),
                ('device_code', models.IntegerField()),
                ('aircraft_code', models.CharField(max_length=36)),
                ('default_launch', models.IntegerField()),
                ('record_modified', models.DateTimeField()),
                ('table', models.CharField(max_length=36)),
                ('meta', models.CharField(max_length=36)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilotlog.user')),
            ],
        ),
    ]
