# Generated by Django 5.0.2 on 2024-02-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0002_alter_aircraft_aircraft_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='category',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='cond_log',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='default_app',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='default_launch',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='default_log',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='default_ops',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='device_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='platform',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='power',
            field=models.IntegerField(null=True),
        ),
    ]
