# Generated by Django 5.0.2 on 2024-02-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0003_alter_aircraft_category_alter_aircraft_cond_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='record_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
