# Generated by Django 5.0.2 on 2024-02-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0004_alter_aircraft__modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='engine_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='gear_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='high_performance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='pressurized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='taa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
